In [1]:
import pandas as pd

In [2]:
games = pd.DataFrame

In [3]:
games

pandas.core.frame.DataFrame

In [4]:
games = pd.read_csv("VGSales.csv")

In [5]:
games

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,90,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.0,0.08,7.81
1,240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.0,0.05,4.50
2,259,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.0,0.05,4.31
3,545,Missile Command,2600,1980.0,Shooter,Atari,2.56,0.17,0.0,0.03,2.76
4,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.0,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16593,16533,Sébastien Loeb Rally Evo,XOne,2016.0,Racing,Milestone S.r.l,0.00,0.01,0.0,0.00,0.01
16594,16534,Hitman (2016),XOne,2016.0,Action,Square Enix,0.00,0.01,0.0,0.00,0.01
16595,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.0,0.00,0.01
16596,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.0,0.00,0.01
16597,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.0,0.00,0.01

In [45]:
juegos = games[games['Rank'] >= 16500]

In [7]:
juegos

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
639,16515,Balloon Pop 2,3DS,2012.0,Puzzle,UFO Interactive,0.01,0.00,0.00,0.0,0.01
640,16531,Kiniro no Corda 3,3DS,2015.0,Adventure,Tecmo Koei,0.00,0.00,0.01,0.0,0.01
641,16538,Mushi Bugyou,3DS,2013.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.0,0.01
642,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.0,0.01
643,16570,Fujiko F. Fujio Characters: Great Assembly! Sl...,3DS,2014.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.0,0.01
...,...,...,...,...,...,...,...,...,...,...,...
16593,16533,Sébastien Loeb Rally Evo,XOne,2016.0,Racing,Milestone S.r.l,0.00,0.01,0.00,0.0,0.01
16594,16534,Hitman (2016),XOne,2016.0,Action,Square Enix,0.00,0.01,0.00,0.0,0.01
16595,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.00,0.0,0.01
16596,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.0,0.01
16597,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.0,0.01

In [10]:
empresa_deseada = "Atari"

In [11]:
print(empresa_deseada)

Atari

In [12]:
juegos = games[games['publisher'] ]

KeyError: 'publisher'

In [15]:
juegos = games[(games['Atari'])]

KeyError: 'Atari'

In [19]:
empresa_deseada = "Atari"
genero_deseado = "Accion"

In [21]:

juegos_atari_accion = games[(games["Atari"] == empresa_deseada) & (games['Accion'] == genero_deseado)]

KeyError: 'Atari'

In [23]:
juegos = games[games['Atari'] < 54]

KeyError: 'Atari'

In [46]:
juegosatari = games[(games["Publisher"]== "Atari") &
                       (games["Genre"]== "Action")]
juegosatari.count()

Rank            54
Nombre          54
Plataforma      54
Year            49
Genre           54
Publisher       54
NA_Sales        54
EU_Sales        54
JP_Sales        54
Other_Sales     54
Global_Sales    54
dtype: int64

In [47]:
juegosfecha = games[(games["Year"] == 1987.0) & (games["Plataforma"] == "NES")]
juegosfecha.count()

Rank            10
Nombre          10
Plataforma      10
Year            10
Genre           10
Publisher       10
NA_Sales        10
EU_Sales        10
JP_Sales        10
Other_Sales     10
Global_Sales    10
dtype: int64

In [48]:
plataformasJuegos = ["PS4", "Wii", "X360"]
generosJuegos = ["Action", "Fighting", "Puzzle"]

plataformas_generos = games[(games["Plataforma"].isin(plataformas)) & (games["Genre"].isin(generos))]
plataformas_generos.count()

Rank            871
Nombre          871
Plataforma      871
Year            854
Genre           871
Publisher       870
NA_Sales        871
EU_Sales        871
JP_Sales        871
Other_Sales     871
Global_Sales    871
dtype: int64

In [36]:
AlSuper = pd.read_csv("supermarket_sales.csv")
AlSuper

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
0,253-12-6086,A,Yangon,Member,Female,Sports and travel,98.40,7,34.4400,$723.24,8.7,Credit card,03/12/2019,12:43:00 p. m.,688.80,4.761905,34.4400
1,276-54-0879,B,Mandalay,Normal,Male,Sports and travel,97.74,4,19.5480,$410.51,6.4,Ewallet,03/12/2019,07:53:00 p. m.,390.96,4.761905,19.5480
2,373-14-0504,A,Yangon,Member,Female,Sports and travel,71.63,2,7.1630,$150.42,8.8,Ewallet,02/12/2019,02:33:00 p. m.,143.26,4.761905,7.1630
3,659-36-1684,C,Naypyitaw,Member,Male,Sports and travel,57.12,7,19.9920,$419.83,6.5,Credit card,01/12/2019,12:02:00 p. m.,399.84,4.761905,19.9920
4,751-15-6198,B,Mandalay,Normal,Male,Sports and travel,23.01,6,6.9030,$144.96,7.9,Ewallet,01/12/2019,04:45:00 p. m.,138.06,4.761905,6.9030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,811-03-8790,A,Naypyitaw,Normal,Female,Electronic accessories,45.48,10,22.7400,$477.54,4.8,Credit card,03/01/2019,10:22:00 a. m.,454.80,4.761905,22.7400
1006,551-21-3069,C,Naypyitaw,Normal,Female,Electronic accessories,23.07,9,10.3815,218.0115,4.9,Cash,02/01/2019,11:27:00 a. m.,207.63,4.761905,10.3815
1007,416-17-9926,A,Naypyitaw,Member,Female,Electronic accessories,74.22,10,37.1100,$779.31,4.3,Credit card,01/01/2019,02:42:00 p. m.,742.20,4.761905,37.1100
1008,556-97-7101,C,Naypyitaw,Normal,Female,Electronic accessories,63.22,2,6.3220,132.762,8.5,Cash,01/01/2019,03:51:00 p. m.,126.44,4.761905,6.3220
1009,891-01-7034,B,Naypyitaw,Normal,Female,Electronic accessories,74.71,6,22.4130,470.673,6.7,Cash,01/01/2019,07:07:00 p. m.,448.26,4.761905,22.4130

In [49]:
consultaciudad = AlSuper[(AlSuper["City"] == "Yangon") & 
                      (AlSuper["Gender"] == "Male") & 
                      (AlSuper["Product line"] == "Sports and travel") & 
                      (AlSuper["Payment"] == "Credit card")]
consultaciudad.count()

Invoice ID                 9
Branch                     9
City                       9
Customer type              9
Gender                     9
Product line               9
Unit price                 9
Quantity                   9
Tax 5%                     9
Total                      9
Rating                     9
Payment                    9
Date                       9
Time                       9
cogs                       9
gross margin percentage    9
gross income               9
dtype: int64

In [50]:
consultaclientes = AlSuper[(AlSuper["City"] == "Naypyitaw") & 
                   (AlSuper["Customer type"] == "Member") & 
                   ((AlSuper["Payment"] == "Cash") | (AlSuper["Payment"] == "Ewallet"))]
consultaclientes.count()

Invoice ID                 109
Branch                     109
City                       109
Customer type              109
Gender                     109
Product line               109
Unit price                 109
Quantity                   109
Tax 5%                     109
Total                      109
Rating                     109
Payment                    109
Date                       109
Time                       109
cogs                       109
gross margin percentage    109
gross income               109
dtype: int64